import Head from "next/head";
import Image from "next/image";

import Header from "../components/Header";
import Container from "../components/Container/Container";

import styles from "../styles/Home.module.scss";

import products from "../data/products.json";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <main>
        <Container>
          <h1>2BadCats</h1>
          <h2>Check em Out</h2>
          <ul className={styles.products}>
            {products.map((product) => {
              return (
                <li key={product.id}>
                  <img src={product.image} alt={`Shot of ${product.title}`} />
                  <h3>{product.title}</h3>
                  <p>${product.price}</p>
                  <p>
                    <button>Add to Cart</button>
                  </p>
                </li>
              );
            })}
          </ul>
        </Container>
      </main>

      <footer className={styles.footer}>
        &copy; 2BadCats, {new Date().getFullYear()}
      </footer>
    </div>
  );
}
